# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-04 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic1',
            new_name='Topic',
        ),
    ]
