# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-05 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='publisher_id',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='topic_id',
            new_name='topic',
        ),
    ]
