# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-06 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20191105_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='留言创建时间'),
        ),
    ]
