# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-01 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191101_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sign',
            field=models.CharField(default='孙悟空', max_length=50, verbose_name='个人签名'),
        ),
    ]
