# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-01 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191101_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sign',
            field=models.CharField(default=user.models.default_sign, max_length=50, verbose_name='个人签名'),
        ),
    ]
